In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('CarPrice.csv')

In [89]:
df.head(10)

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
0,1,alfa-romero giulia,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,13495
1,2,alfa-romero stelvio,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,16500
2,3,alfa-romero Quadrifoglio,gas,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,154,19,26,16500
3,4,audi 100 ls,gas,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,102,24,30,13950
4,5,audi 100ls,gas,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,3,136,mpfi,115,18,22,17450
5,6,audi fox,gas,2,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,5,136,mpfi,110,19,25,15250
6,7,audi 100ls,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,5,136,mpfi,110,19,25,17710
7,8,audi 5000,gas,4,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,5,136,mpfi,110,19,25,18920
8,9,audi 4000,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,5,131,mpfi,140,17,20,23875
9,10,audi 5000s (diesel),gas,2,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,5,131,mpfi,160,16,22,17859

In [93]:
df['CarName'] = df['CarName'].str.lower()

In [95]:
df.sort_values(by=['CarName'])

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
0,1,alfa-romero giulia,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,13495
2,3,alfa-romero quadrifoglio,gas,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,154,19,26,16500
1,2,alfa-romero stelvio,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,16500
3,4,audi 100 ls,gas,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,102,24,30,13950
4,5,audi 100ls,gas,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,3,136,mpfi,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,volvo 264gl,gas,4,sedan,rwd,front,104.3,188.8,67.2,56.2,3045,ohc,4,130,mpfi,162,17,22,18420
204,205,volvo 264gl,gas,4,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,4,141,mpfi,114,19,25,22625
199,200,volvo diesel,gas,4,wagon,rwd,front,104.3,188.8,67.2,57.5,3157,ohc,4,130,mpfi,162,17,22,18950
189,190,vw dasher,gas,2,convertible,fwd,front,94.5,159.3,64.2,55.6,2254,ohc,4,109,mpfi,90,24,29,11595
190,191,vw rabbit,gas,2,hatchback,fwd,front,94.5,165.7,64.0,51.4,2221,ohc,4,109,mpfi,90,24,29,9980

In [96]:
df.loc[df['car_ID'] == 98]

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
97,98,nissan note,gas,4,wagon,fwd,front,94.5,170.2,63.8,53.5,2037,ohc,4,97,2bbl,69,31,37,7999

In [97]:
df.loc[df['CarName'] == 'nissan note']

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
97,98,nissan note,gas,4,wagon,fwd,front,94.5,170.2,63.8,53.5,2037,ohc,4,97,2bbl,69,31,37,7999

In [98]:
df.head(10)

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
0,1,alfa-romero giulia,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,13495
1,2,alfa-romero stelvio,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,16500
2,3,alfa-romero quadrifoglio,gas,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,154,19,26,16500
3,4,audi 100 ls,gas,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,102,24,30,13950
4,5,audi 100ls,gas,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,3,136,mpfi,115,18,22,17450
5,6,audi fox,gas,2,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,5,136,mpfi,110,19,25,15250
6,7,audi 100ls,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,5,136,mpfi,110,19,25,17710
7,8,audi 5000,gas,4,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,5,136,mpfi,110,19,25,18920
8,9,audi 4000,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,5,131,mpfi,140,17,20,23875
9,10,audi 5000s (diesel),gas,2,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,5,131,mpfi,160,16,22,17859

In [99]:
body_type_car = df['carbody'].values
renewed_body = set(body_type_car)

In [100]:
print(renewed_body)

{'wagon', 'sedan', 'hatchback', 'convertible', 'hardtop'}

In [104]:
mywagon = df.loc[df['carbody'] == 'wagon']

In [108]:
mywagon.price.sum()

309299