In [11]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('CarPrice.csv')

In [3]:
df.head(10)

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
0,1,alfa-romero giulia,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,13495
1,2,alfa-romero stelvio,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,16500
2,3,alfa-romero Quadrifoglio,gas,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,154,19,26,16500
3,4,audi 100 ls,gas,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,102,24,30,13950
4,5,audi 100ls,gas,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,3,136,mpfi,115,18,22,17450
5,6,audi fox,gas,2,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,5,136,mpfi,110,19,25,15250
6,7,audi 100ls,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,5,136,mpfi,110,19,25,17710
7,8,audi 5000,gas,4,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,5,136,mpfi,110,19,25,18920
8,9,audi 4000,gas,4,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,5,131,mpfi,140,17,20,23875
9,10,audi 5000s (diesel),gas,2,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,5,131,mpfi,160,16,22,17859

In [31]:
df.loc[df['car_ID'] == 8]

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
7,8,audi 5000,gas,4,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,5,136,mpfi,110,19,25,18920

In [24]:
def cyclinders():
    cy = df['cylindernumber'].values
    return cy 
all_cylinders = []
for items in cyclinders():
    all_cylinders.append(items)
print(set(all_cylinders))

{2, 3, 4, 5, 6, 8, 12}

In [34]:
#df.loc[df['cylindernumber'] == 8]

for items in set(df['cylindernumber']):
    print(items)

2
3
4
5
6
8
12

In [19]:
values = np.array(df.columns)

count = 0 
for i in values:
    if count < len(values):
        print ("{} : {}".format(count, i))
    count +=1

0 : car_ID
1 : CarName
2 : fueltype
3 : doornumber
4 : carbody
5 : drivewheel
6 : enginelocation
7 : wheelbase
8 : carlength
9 : carwidth
10 : carheight
11 : curbweight
12 : enginetype
13 : cylindernumber
14 : enginesize
15 : fuelsystem
16 : horsepower
17 : citympg
18 : highwaympg
19 : price

In [38]:
#df.loc[df['carbody']]
body_types = df['carbody'].values
set(body_types)

{'convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'}

In [43]:
df.loc[df['carbody'] == 'wagon']

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
7,8,audi 5000,gas,4,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,5,136,mpfi,110,19,25,18920
28,29,dodge dart custom,gas,4,wagon,fwd,front,103.3,174.6,64.6,59.8,2535,ohc,4,122,2bbl,88,24,30,8921
36,37,honda civic 1500 gl,gas,4,wagon,fwd,front,96.5,157.1,63.9,58.3,2024,ohc,4,92,1bbl,76,30,34,7295
68,69,buick century luxus (sw),diesel,4,wagon,rwd,front,110.0,190.9,70.3,58.7,3750,ohc,5,183,idi,123,22,25,28248
93,94,nissan titan,gas,4,wagon,fwd,front,94.5,170.2,63.8,53.5,2024,ohc,4,97,2bbl,69,31,37,7349
97,98,nissan note,gas,4,wagon,fwd,front,94.5,170.2,63.8,53.5,2037,ohc,4,97,2bbl,69,31,37,7999
102,103,nissan fuga,gas,4,wagon,fwd,front,100.4,184.6,66.5,56.1,3296,ohcv,6,181,mpfi,152,17,22,14399
109,110,peugeot 504 (sw),gas,4,wagon,rwd,front,114.2,198.9,68.4,58.7,3230,l,4,120,mpfi,97,19,24,12440
110,111,peugeot 504,diesel,4,wagon,rwd,front,114.2,198.9,68.4,58.7,3430,l,4,152,idi,95,25,25,13860
113,114,peugeot 504,gas,4,wagon,rwd,front,114.2,198.9,68.4,56.7,3285,l,4,120,mpfi,95,19,24,16695
114,115,peugeot 505s turbo diesel,diesel,4,wagon,rwd,front,114.2,198.9,68.4,58.7,3485,l,4,152,idi,95,25,25,17075
123,124,plymouth valiant,gas,4,wagon,fwd,front,103.3,174.6,64.6,59.8,2535,ohc,4,122,2bbl,88,24,30,8921
130,131,renault 12tl,gas,4,wagon,fwd,front,96.1,181.5,66.5,55.2,2579,ohc,4,132,mpfi,90,23,31,9295
146,147,subaru trezia,gas,4,wagon,fwd,front,97.0,173.5,65.4,53.0,2290,ohcf,4,108,2bbl,82,28,32,7463
147,148,subaru tribeca,gas,4,wagon,fwd,front,97.0,173.5,65.4,53.0,2455,ohcf,4,108,mpfi,94,25,31,10198
148,149,subaru dl,gas,4,wagon,4wd,front,96.9,173.6,65.4,54.9,2420,ohcf,4,108,2bbl,82,23,29,8013
149,150,subaru dl,gas,4,wagon,4wd,front,96.9,173.6,65.4,54.9,2650,ohcf,4,108,mpfi,111,23,23,11694
153,154,toyota corona hardtop,gas,4,wagon,fwd,front,95.7,169.7,63.6,59.1,2280,ohc,4,92,2bbl,62,31,37,6918
154,155,toyota corolla 1600 (sw),gas,4,wagon,4wd,front,95.7,169.7,63.6,59.1,2290,ohc,4,92,2bbl,62,27,32,7898
155,156,toyota carina,gas,4,wagon,4wd,front,95.7,169.7,63.6,59.1,3110,ohc,4,92,2bbl,62,27,32,8778
181,182,toyouta tercel,gas,4,wagon,rwd,front,104.5,187.8,66.5,54.1,3151,dohc,6,161,mpfi,156,19,24,15750
193,194,volkswagen dasher,gas,4,wagon,fwd,front,100.4,183.1,66.9,55.1,2563,ohc,4,109,mpfi,88,25,31,12290
195,196,volvo 144ea,gas,4,wagon,rwd,front,104.3,188.8,67.2,57.5,3034,ohc,4,141,mpfi,114,23,28,13415
197,198,volvo 245,gas,4,wagon,rwd,front,104.3,188.8,67.2,57.5,3042,ohc,4,141,mpfi,114,24,28,16515
199,200,volvo diesel,gas,4,wagon,rwd,front,104.3,188.8,67.2,57.5,3157,ohc,4,130,mpfi,162,17,22,18950

In [45]:
df_2 = df[["car_ID","CarName","fueltype"]]

In [46]:
df_2

     car_ID                   CarName fueltype
0         1        alfa-romero giulia      gas
1         2       alfa-romero stelvio      gas
2         3  alfa-romero Quadrifoglio      gas
3         4               audi 100 ls      gas
4         5                audi 100ls      gas
..      ...                       ...      ...
200     201           volvo 145e (sw)      gas
201     202               volvo 144ea      gas
202     203               volvo 244dl      gas
203     204                 volvo 246   diesel
204     205               volvo 264gl      gas

[205 rows x 3 columns]

In [51]:
from getDatPDDF import getCarasPDDF, getDataColumns

df = getCarasPDDF()
col = getDataColumns()
df[col[0]]

0        1
1        2
2        3
3        4
4        5
      ...
200    201
201    202
202    203
203    204
204    205
Name: car_ID, Length: 205, dtype: int64

In [55]:
df.loc[df['car_ID'] == 45]

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
44,45,isuzu D-Max,gas,2,sedan,fwd,front,94.5,155.9,63.6,52.0,1874,ohc,4,90,2bbl,70,38,43,8916