In [70]:
from loaddata import df_header, data_set
from getDatPDDF import getCarasPDDF

#Get Car value by ID
def getCarbyID():
    # I am using this check to keep track of  index in my records index
    checker  = 1
    try:
        id = int(input("Enter the ID of the Car you want to view: "))
        # index in a list starts from zero, but the car index starts from one , so i need to subtract id  from my checker variable
        id = id - checker
        return data_set[id][:] # return the list of car records  according to the input id - id = id - checker
    except BaseException as error:
        print("Your Error Message reads: {}".format(error))


def displayCarDataQuerybyID():
    # the block below is ussed to display each column header and the the corresponding value of the header based on the input ID
    try:
        car_id_details = []
        for items in getCarbyID(): #function is called based on the method defined above
            car_id_details.append(items)
        car_record = zip(df_header,car_id_details) # the zip function is used to create a dictionary of the data column header and the corresponding records associated to the column header
        for ID,car_details in  dict(car_record).items():
            print("The {} of the car is: {}".format(ID,car_details)) #print the result in form of a text  statement
    except BaseException as error:
        print("The following error occured: {}".format(error))

if __name__ == "__main__":
    displayCarDataQuerybyID() #display individual car details by ID method is called here -1

The car_ID of the car is: 90
The CarName of the car is: Nissan versa
The fueltype of the car is: gas
The doornumber of the car is: 2
The carbody of the car is: sedan
The drivewheel of the car is: fwd
The enginelocation of the car is: front
The wheelbase of the car is: 94.5
The carlength of the car is: 165.3
The carwidth of the car is: 63.8
The carheight of the car is: 54.5
The curbweight of the car is: 1889
The enginetype of the car is: ohc
The cylindernumber of the car is: 4
The enginesize of the car is: 97
The fuelsystem of the car is: 2bbl
The horsepower of the car is: 69
The citympg of the car is: 31
The highwaympg of the car is: 37
The price of the car is: 5499

In [21]:
from getDatPDDF import getCarasPDDF # import the data frame variable from the 
from loaddata import df_header
from IPython.display import display

df = getCarasPDDF() # This variable assigns the value from the return value gotten from the getCarasPDDF function from the getDatPDDF module

#below we define a function with parameter that takes cylinder as a paramter to get the number of cylinders a given car has
# This function is called in the getCarbyCylinderNumber function below
def chooseCylindertoDisplay(cylinder):
    try:
        car_by_cylinder_num = df.loc[df["cylindernumber"] == cylinder]
        return car_by_cylinder_num
    except BaseException as error:
        print("The following error occured {}".format(error))

# function below handles all logic responsible for getting cars with a particulare cylinder number
def getCarbyCylinderNumber():
    # cylinder_numbers = []
    # try:
    #     for cylinder_num in df["cylindernumber"]:
    #         cylinder_numbers.append(cylinder_num)
    #     unique_cylinder_numbers  =  list(set(cylinder_numbers))
    # except BaseException as error:
    #     print("The following error occured {}".format(error))
    #The line below, get the unique cylinder numbers using set () from the data frame index to the cylinder numbe
    unique_cylinder_numbers = [cylinders for cylinders in set(df["cylindernumber"])]
    # the block below under the tr and except block will
    # give menu displaying cyliner options available for analysis in the data set
    # vallidate the user entry
    # allow the user to exit this program if they change their mind on running the program
    try:
        choice = int(input("We have cars with a set of cylinder number, press 1 to view them or press 2 to quite - please enter an Integer"))
        if choice == 1:
            # The code below is a menu that enables the user view the Car cylinder options available in the data set
            for cylinders in range(len(unique_cylinder_numbers)):
                print("enter {} to view cars with {} cylinders".format(unique_cylinder_numbers[cylinders],unique_cylinder_numbers[cylinders]))
            
            # Enter the cylinder type you want to view
            cylinder_choice = int(input("Enter a cylinder number for cars under this category: "))
            # input validation used to verify that the user has entered a cylinder number within the range of cylinder numbers in
            # given in the unique _cylinder_number variable 
            if cylinder_choice not in unique_cylinder_numbers: 
                print("Your Selected option is invalid")
            else:                
                display(chooseCylindertoDisplay(cylinder_choice))
    
        elif choice == 2:
            print("You have exited this menu\n")
            print("Thank you for testing my functionalities!")
            
        else:
            print("Your input is invalid")
    except BaseException as error:
        print("The following error occured {}".format(error))

if __name__ == "__main__":
    getCarbyCylinderNumber()

You have exited this menu

Thank you for testing my functionalities!

In [72]:
# The code block gets all cars with specific body type
from getBodytype import getUniqueBodyType
from getDatPDDF import getCarasPDDF #gets the car assessment data frame
from loaddata import df_header # Gets the column list from load data module

car_body_type = getUniqueBodyType() # assign the unique car body type to the variable car_body_type
cardf = getCarasPDDF()
#The method retrieveCarsBody is used to access a group of cars with same body type. 
# The body choice vairable allows the user enter an int value to view cars under diffrent body type as was retrieved from car dataframe (cardf)

def retrieveCarsBody():
    try:
        print("The following Body types are available {}".format(car_body_type))
        bodychoice = int(input("Enter 1 for {} \n, Enter 2 for {} \n, Enter 3 for {} \n, Enter 4 for {} \n, Enter 5 for {} \n".format(car_body_type[0],car_body_type[1],car_body_type[2],car_body_type[3],car_body_type[4])))
        
        # menu option for the different car body type
        # cardf.loc[cardf[df_header[4]] is used to get the Carbody type header from the list of columns
        # car_body_type[x], where x = 0 to 4 is used to get the specific car body types from the car_body_type list
        if bodychoice == 1:
            display(cardf.loc[cardf[df_header[4]]== car_body_type[0]])
        elif bodychoice == 2:
            display(cardf.loc[cardf[df_header[4]]== car_body_type[1]])
        elif bodychoice == 3:
            display(cardf.loc[cardf[df_header[4]]== car_body_type[2]])
        elif bodychoice == 4:
            display(cardf.loc[cardf[df_header[4]]== car_body_type[3]])
        elif bodychoice == 5:
            display(cardf.loc[cardf[df_header[4]]== car_body_type[4]])
        else:
            print("Your input is invalid")
    except BaseException as error:
        print("The following error has occurred: {}".format(error))    

if __name__ == "__main__":
    retrieveCarsBody()

The following Body types are available ['convertible', 'sedan', 'hardtop', 'wagon', 'hatchback']

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
69,70,buick century,diesel,2,hardtop,rwd,front,106.7,187.5,70.3,54.9,3495,ohc,5,183,idi,123,22,25,28176
74,75,buick regal sport coupe (turbo),gas,2,hardtop,rwd,front,112.0,199.2,72.0,55.4,3715,ohcv,8,304,mpfi,184,14,16,45400
98,99,nissan clipper,gas,2,hardtop,fwd,front,95.1,162.4,63.8,53.3,2008,ohc,4,97,2bbl,69,31,37,8249
126,127,porcshce panamera,gas,2,hardtop,rwd,rear,89.5,168.9,65.0,51.6,2756,ohcf,6,194,mpfi,207,17,25,32528
127,128,porsche cayenne,gas,2,hardtop,rwd,rear,89.5,168.9,65.0,51.6,2756,ohcf,6,194,mpfi,207,17,25,34028
167,168,toyota corona liftback,gas,2,hardtop,rwd,front,98.4,176.2,65.6,52.0,2540,ohc,4,146,mpfi,116,24,30,8449
168,169,toyota corolla,gas,2,hardtop,rwd,front,98.4,176.2,65.6,52.0,2536,ohc,4,146,mpfi,116,24,30,9639
170,171,toyota tercel,gas,2,hardtop,rwd,front,98.4,176.2,65.6,52.0,2679,ohc,4,146,mpfi,116,24,30,11199

In [73]:
from getDatPDDF import getCarasPDDF, getDataColumns
from sys import exit

cardata = getCarasPDDF()
dfcolumns = getDataColumns()

def getSpecColumnsbyCarID():
    print("You can only enter a maximum of 5 columns")
    print("Select the column you want to display for a given car ID")
    print("\n")
    col_count = 0
    while col_count < len(dfcolumns):
        print("Enter option {} to see {} column in your feature set".format(col_count+1,dfcolumns[col_count] ))
        col_count +=1
    # your must enter a set of 5 numbers corresponding to the the column you are interested
    # in displaying for a given car ID
    try:
        entry_count = 0 # collection of options for column to view
        col_option_list = [1] # list to hold our choices, option 1 in this list already reserves a space for the carIDvariable
        # The while block is used to get a set of column input in int that represents column values that the user wants retireved 
        # This will be columns related to an indivual car
        while entry_count < 5:
            choice = int(input("Enter the value for the columns you want to display: "))
            # The last element of our column list is on index 19 which is 20
            # The if block validates whether the user's input is more than 20 
            if choice > 20:
                print("Your Column input should not be more than 20 (Index of the last Column element)")
                break
            if choice not in col_option_list: # condition to check and confirm that no same number is entered twice
                col_option_list.append(choice)
            else:
                print("Please select unique columns")
                break
            entry_count += 1

        if len(col_option_list) == 6: # the sixth value is the CarID value that will be part of the program's display result
            car_id_choice = int(input("Enter the Car ID you want to display its details for the columns above")) # get the Car ID from the Use
        else:
            print("\n")
            print("The code is exiting .............")
            exit()

        # The new_car_df variable below is formated create a sub data frame from that original data frame that enables our program display our selected columns
        new_car_df = cardata[[dfcolumns[0],dfcolumns[col_option_list[0]],dfcolumns[col_option_list[1]],dfcolumns[col_option_list[2]],dfcolumns[col_option_list[3]],dfcolumns[col_option_list[4]]]] # create new data frame with the selected user columns
        display(new_car_df.loc[new_car_df[dfcolumns[0]] == car_id_choice])
        
    except BaseException as error:
        print("\n")
        print("The following error has occured: {}".format(error))

if __name__ == "__main__":
    getSpecColumnsbyCarID()

You can only enter a maximum of 5 columns
Select the column you want to display for a given car ID


Enter option 1 to see car_ID column in your feature set
Enter option 2 to see CarName column in your feature set
Enter option 3 to see fueltype column in your feature set
Enter option 4 to see doornumber column in your feature set
Enter option 5 to see carbody column in your feature set
Enter option 6 to see drivewheel column in your feature set
Enter option 7 to see enginelocation column in your feature set
Enter option 8 to see wheelbase column in your feature set
Enter option 9 to see carlength column in your feature set
Enter option 10 to see carwidth column in your feature set
Enter option 11 to see carheight column in your feature set
Enter option 12 to see curbweight column in your feature set
Enter option 13 to see enginetype column in your feature set
Enter option 14 to see cylindernumber column in your feature set
Enter option 15 to see enginesize column in your feature set
Enter option 16 to see fuelsystem column in your feature set
Enter option 17 to see horsepower column in your feature set
Enter option 18 to see citympg column in your feature set
Enter option 19 to see highwaympg column in your feature set
Enter option 20 to see price column in your feature set

    car_ID         CarName  cylindernumber fueltype drivewheel enginelocation
98      99  nissan clipper               4      gas        fwd          front

In [1]:
from getDatPDDF import getCarNames

#This method calls the getCarNames function from the getDataPDDF module
#It retrieves the cleaned data that returns the Car names in alphabetical order
def sortCarbyAlph():    
    try:
        names = getCarNames()
        return names
    except BaseException as error:
        print("The following error occured: {}".format(error))
        
sortCarbyAlph()

,car_ID,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,horsepower,citympg,highwaympg,price
0,1,alfa-romero giulia,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,13495
2,3,alfa-romero quadrifoglio,gas,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,154,19,26,16500
1,2,alfa-romero stelvio,gas,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,111,21,27,16500
3,4,audi 100 ls,gas,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,102,24,30,13950
4,5,audi 100ls,gas,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,3,136,mpfi,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,volvo 264gl,gas,4,sedan,rwd,front,104.3,188.8,67.2,56.2,3045,ohc,4,130,mpfi,162,17,22,18420
204,205,volvo 264gl,gas,4,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,4,141,mpfi,114,19,25,22625
199,200,volvo diesel,gas,4,wagon,rwd,front,104.3,188.8,67.2,57.5,3157,ohc,4,130,mpfi,162,17,22,18950
189,190,vw dasher,gas,2,convertible,fwd,front,94.5,159.3,64.2,55.6,2254,ohc,4,109,mpfi,90,24,29,11595
190,191,vw rabbit,gas,2,hatchback,fwd,front,94.5,165.7,64.0,51.4,2221,ohc,4,109,mpfi,90,24,29,9980